# 本番環境用のdocker-compose設定
# 本番環境では外部のマネージドサービス（RDS、S3等）を使用し、
# アプリケーションコンテナのみを実行します

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: memo-app-prod
    restart: always
    ports:
      - "80:8000"
    environment:
      - GIN_MODE=release
      - SERVER_PORT=8000
      - DB_HOST=${DB_HOST:-localhost} # 外部RDSのエンドポイント
      - DB_PORT=${DB_PORT:-5432}
      - DB_USER=${DB_USER:-memo_user}
      - DB_PASSWORD=${DB_PASSWORD} # 必須: 環境変数から取得
      - DB_NAME=${DB_NAME:-memo_db}
      - DB_SSLMODE=${DB_SSLMODE:-require} # 本番環境ではSSL必須
      - S3_ENDPOINT=${S3_ENDPOINT:-} # 空の場合はAWS S3を使用
      - S3_ACCESS_KEY_ID=${S3_ACCESS_KEY_ID} # AWS認証情報
      - S3_SECRET_ACCESS_KEY=${S3_SECRET_ACCESS_KEY}
      - S3_REGION=${S3_REGION:-ap-northeast-1}
      - S3_BUCKET=${S3_BUCKET:-memo-app-logs-prod}
      - S3_USE_SSL=${S3_USE_SSL:-true}
      - LOG_LEVEL=${LOG_LEVEL:-warn} # 本番環境では警告レベル以上
      - LOG_UPLOAD_ENABLED=${LOG_UPLOAD_ENABLED:-true}
      - LOG_UPLOAD_MAX_AGE=${LOG_UPLOAD_MAX_AGE:-1h}
      - LOG_UPLOAD_INTERVAL=${LOG_UPLOAD_INTERVAL:-30m}
      - DOCKER_CONTAINER=true # Docker環境であることを明示
    # EC2 t2.microに最適化したリソース制限
    deploy:
      resources:
        limits:
          cpus: '0.8' # appのみなので多めに割り当て
          memory: 800M
        reservations:
          cpus: '0.2'
          memory: 128M
    healthcheck:
      test: [ "CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8000/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    # 本番環境用のボリューム（ログ保存用）
    volumes:
      - app_logs:/app/logs

  # 自動更新サービス（オプション）
  watchtower:
    image: containrrr/watchtower:latest
    container_name: memo-watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_POLL_INTERVAL=300 # 5分間隔でチェック
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_INCLUDE_STOPPED=true
      - WATCHTOWER_MONITOR_ONLY=true # 監視のみ（自動更新しない）
    command: memo-app-prod
    profiles:
      - monitoring

volumes:
  app_logs:
    driver: local

# 本番環境では外部サービスを使用するためネットワーク設定は最小限
networks:
  default:
    driver: bridge
